trigger:
- main

pool: Default

steps:

  - script: terraform fmt -check -recursive
        displayName:"Terraform Format"
  - script: terraform validate
      displayName:"Terraform Validate"
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: 'latest'
  
  # - task: TerraformTask@5
  #   inputs:
  #     provider: 'azurerm'
  #     command: 'custom'
  #     outputTo: 'console'
  #     customCommand: 'terraform fmt'
  #     environmentServiceNameAzureRM: 'sep-serviceconection'
  # - task: TerraformTask@5
  #   inputs:
  #     provider: 'azurerm'
  #     command: 'validate'
  - task: tfsec@1
    displayName: Scaning stage
    inputs:
      version: 'v1.26.0'

