trigger:
- main

pool: Default

steps:

  - script: terraform fmt -check -recursive
        displayName:"Terraform Format"
  - script: terraform validate
      displayName:"Terraform Validate"

  - task: tfsec@1
    displayName: Scaning stage
    inputs:
      version: 'v1.26.0'

